export const districtNames = [
  'Quetta District',
  'Sibi District',
  'Nasirabad District',
  'Zhob District',
  'Bannu District',
  'D. I. Khan District',
  'Mardan District',
  'Peshawar District',
  'Hyderabad District',
  'Larkana District',
  'Mirpur Khas District',
  'Sukkur District',
  'Awaran District',
  'Barkhan District',
  'Bolan District',
  'Chagai District',
  'Dera Bugti District',
  'Jaffarabad District',
  'Jhal Magsi District',
  'Kalat District',
  'Gwadar District',
  'Kech District',
  'Kharan District',
  'Khuzdar District',
  'Killa Abdullah District',
  'Killa Saifullah District',
  'Kohlu District',
  'Loralai District',
  'Mastung District',
  'Lasbela District',
  'Musakhel District',
  'Panjgur District',
  'Ziarat District',
  'Pishin District',
  'Bajaur Agency',
  'Khyber Agency',
  'Kurram Agency',
  'Mohmand Agency',
  'North Waziristan Agency',
  'Orakzai Agency',
  'T.A.Adj.Lakki Marwat District',
  'South Waziristan Agency',
  'Tribal Area Adj Bannu District',
  'Tribal Area Adj D.I.Khan Distt',
  'Tribal Area Adj Kohat District',
  'Tribal Area Adj Peshawar Distt',
  'Tribal Area Adj Tank Distt',
  'Islamabad District',
  'Abbottabad District',
  'Charsadda District',
  'Batagram District',
  'Buner District',
  'Hangu District',
  'Haripur District',
  'Karak District',
  'Chitral District',
  'Kohistan District',
  'Lakki Marwat District',
  'Kohat District',
  'Lower Dir District',
  'Mansehra District',
  'Nowshera District',
  'Swabi District',
  'Swat District',
  'Tank District',
  'Shangla District',
  'Upper Dir District',
  'Malakand Protected Area',
  'Attock District',
  'Bahawalnagar District',
  'Bahawalpur District',
  'Dera Ghazi Khan District',
  'Faisalabad District',
  'Bhakkar District',
  'Chakwal District',
  'Gujranwala District',
  'Gujrat District',
  'Jhelum District',
  'Jhang District',
  'Kasur District',
  'Hafizabad District',
  'Khanewal District',
  'Khushab District',
  'Lahore District',
  'Layyah District',
  'Mianwali District',
  'Lodhran District',
  'Mandi Bahauddin District',
  'Multan District',
  'Muzaffargarh District',
  'Narowal District',
  'Okara District',
  'Pakpattan District',
  'Rahim Yar Khan District',
  'Sargodha District',
  'Rajanpur District',
  'Rawalpindi District',
  'Sahiwal District',
  'Sheikhupura District',
  'Vehari District',
  'Toba Tek Singh District',
  'Sialkot District',
  'Badin District',
  'Dadu District',
  'Ghotki District',
  'Karachi Central District',
  'Jacobabad District',
  'Karachi East District',
  'Karachi South District',
  'Karachi West District',
  'Khairpur District',
  'Malir District',
  'Naushahro Feroze District',
  'Nawabshah District',
  'Sanghar District',
  'Shikarpur District',
  'Tharparkar District',
  'Umer Kot District',
  'Thatta District',
]
